name: mwardi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  internet_connection_checker:
  table_calendar:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  curved_navigation_bar: ^1.0.3
  top_snackbar_flutter: ^3.0.0+1
  connectivity_plus: ^3.0.2
  firebase_messaging:
  firebase_core:
  shared_preferences: ^2.0.16
  http: ^0.13.5
  barbecue: ^0.4.0

  slider_button:
    git:
      url: https://github.com/HaniMohamed/Slider-Button.git
  ansicolor: ^2.0.1
  mime: ^1.0.4
  flutter_svg:
  device_info_plus: ^8.1.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+2

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
